# Generated by Django 4.2 on 2023-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CofrajMetalics',
            fields=[
                ('CofrajMetalicId', models.AutoField(primary_key=True, serialize=False)),
                ('CofrajMetalicName', models.CharField(max_length=100)),
                ('CofrajMetalicCantitate', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CofrajtTipDokas',
            fields=[
                ('CofrajtTipDokaId', models.AutoField(primary_key=True, serialize=False)),
                ('CofrajtTipDokaName', models.CharField(max_length=100)),
                ('CofrajtTipDokaCantitate', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combustibils',
            fields=[
                ('CombustibilId', models.AutoField(primary_key=True, serialize=False)),
                ('CombustibilName', models.CharField(max_length=100)),
                ('CombustibilCantitate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('ConsumeId', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('MaterialSerie', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('MaterialAmount', models.FloatField(null=True)),
                ('GiveRecive', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('HistoryId', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100)),
                ('Tool', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('ToolSerie', models.CharField(max_length=100, null=True)),
                ('GiveRecive', models.CharField(max_length=100, null=True)),
                ('Pieces', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorieScheles',
            fields=[
                ('HistoriesScheleId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('CombustibilCantitate', models.CharField(max_length=100)),
                ('DateSchela', models.DateField()),
                ('Directie', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('MaterialId', models.AutoField(primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=100)),
                ('Quantity', models.FloatField()),
                ('Amount', models.FloatField()),
                ('MaterialLocation', models.CharField(max_length=100)),
                ('Provider', models.CharField(max_length=500, null=True)),
                ('DateOfGiving', models.DateField(null=True)),
                ('OneUnity', models.FloatField(null=True)),
                ('UnityOfMesurment', models.CharField(max_length=500, null=True)),
                ('TypeOfUnityOfMesurment', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MijloaceFixes',
            fields=[
                ('MijloaceFixeId', models.AutoField(primary_key=True, serialize=False)),
                ('MijloaceFixeName', models.CharField(max_length=100)),
                ('MijloaceFixeCantitate', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Popis',
            fields=[
                ('PopiDokaId', models.AutoField(primary_key=True, serialize=False)),
                ('PopiName', models.CharField(max_length=100)),
                ('PopiCantitate', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchelaFatadaModularas',
            fields=[
                ('SchelaFatadaModularaId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaFatadaModularaName', models.CharField(max_length=100)),
                ('SchelaFatadaModularaCantitate', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchelaFatadas',
            fields=[
                ('SchelaFatadaId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaFatadaName', models.CharField(max_length=100)),
                ('SchelaFatadaCantitate', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchelaUsoaras',
            fields=[
                ('SchelaUsoaraId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaUsoaraName', models.CharField(max_length=100)),
                ('SchelaUsoaraCantitate', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('ShedId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('Pin', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Pieces', models.IntegerField()),
                ('Provider', models.CharField(max_length=500, null=True)),
                ('Components', models.CharField(max_length=500, null=True)),
                ('Detail', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('ToolId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('Detail', models.CharField(max_length=500, null=True)),
                ('Pieces', models.IntegerField(null=True)),
                ('MainLocation', models.CharField(max_length=500, null=True)),
                ('Provider', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unfunctional',
            fields=[
                ('UnfunctionalId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('Detail', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=100)),
                ('Service', models.CharField(max_length=500)),
                ('Pieces', models.IntegerField()),
                ('Provider', models.CharField(max_length=500, null=True)),
                ('Components', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('UserSerie', models.CharField(max_length=100)),
                ('UserPin', models.CharField(max_length=100)),
                ('NameAndSerie', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('WorkFieldId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('Pin', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Pieces', models.IntegerField()),
                ('Provider', models.CharField(max_length=500, null=True)),
                ('Components', models.CharField(max_length=500, null=True)),
                ('Detail', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
