"""Generate identical employee UI copy for Angular and Android. No network required."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LANGUAGES = ('ro', 'en', 'pa', 'hi', 'ne', 'bn')

def outputs(android):
    catalog = json.loads(Path(__file__).with_name('employee-ui.json').read_text())
    for key, values in catalog.items():
        assert len(values) == len(LANGUAGES) and all(isinstance(v, str) and v.strip() for v in values), key
    packs = {lang: {key: values[i] for key, values in catalog.items()} for i, lang in enumerate(LANGUAGES)}
    web = ROOT / 'Inventory-and-bill-proccesor-main/FE/newface/src/app/i18n/employee-copy.ts'
    yield web, '// Generated by scripts/localization/generate.py; edit employee-ui.json.\nexport const employeeCopy = ' + json.dumps(packs, ensure_ascii=False, indent=2) + ' as const;\n'
    kotlin = '// Generated by dmxnew/scripts/localization/generate.py; edit employee-ui.json.\npackage com.dmx.clockin\n\ninternal data class EmployeeUiCopy(\n' + ''.join(f'    val {key}: String,\n' for key in catalog) + ')\n\ninternal fun employeeUi(language: AppLanguage): EmployeeUiCopy = when (language) {\n'
    for lang, pack in packs.items():
        kotlin += f'    AppLanguage.{lang.title()} -> EmployeeUiCopy(\n'
        kotlin += ''.join(f'        {key} = {json.dumps(value, ensure_ascii=False)},\n' for key, value in pack.items())
        kotlin += '    )\n'
    yield android / 'dmx_android/app/src/main/java/com/dmx/clockin/EmployeeUiCopy.kt', kotlin + '}\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--android', type=Path, default=ROOT.parent / 'android_dmx')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in outputs(args.android):
        if args.check:
            assert path.read_text() == content, f'Outdated translations: {path}'
        else:
            path.write_text(content)
        print(path)
