# Generated by Django 4.0.3 on 2022-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('HistoryId', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=100)),
                ('Tool', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('ToolId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('Pin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('UserSerie', models.CharField(max_length=100)),
                ('UserPin', models.CharField(max_length=100)),
            ],
        ),
    ]
