# Generated by Django 4.0.3 on 2022-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='UserID',
            new_name='UserId',
        ),
    ]
