# Generated by Django 4.0.3 on 2022-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0007_consumables_materials_dateofgiving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='GiveRecive',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consumables',
            name='MaterialAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='OneUnity',
            field=models.IntegerField(null=True),
        ),
    ]
