# Generated by Django 4.0.3 on 2022-04-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0008_consumables_giverecive_consumables_materialamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='UserSerie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='histories',
            name='UserSerie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='Service',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
