# Generated by Django 4.0.3 on 2022-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0010_remove_consumables_userserie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='UserNameSerie',
        ),
        migrations.AddField(
            model_name='users',
            name='NameAndSerie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
