# Generated by Django 4.0.3 on 2022-04-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0011_remove_users_usernameserie_users_nameandserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='BillNumber',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='materials',
            name='UnityOfMesurment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='Service',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
