# Generated by Django 4.0.3 on 2022-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0012_materials_billnumber_materials_unityofmesurment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='TypeOfUnityOfMesurment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
