# Generated by Django 4.0.3 on 2022-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0013_materials_typeofunityofmesurment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='MainLocation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='Pieces',
            field=models.IntegerField(null=True),
        ),
    ]
