# Generated by Django 4.0.3 on 2022-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0014_tools_mainlocation_tools_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='histories',
            name='GiveRecive',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='histories',
            name='Pieces',
            field=models.IntegerField(null=True),
        ),
    ]
