# Generated by Django 4.0.3 on 2022-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0015_histories_giverecive_histories_pieces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('ShedId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('Pin', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Pieces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unfunctional',
            fields=[
                ('ToolId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('Detail', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=100)),
                ('Service', models.CharField(max_length=500)),
                ('Pieces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('WorkFieldId', models.AutoField(primary_key=True, serialize=False)),
                ('ToolSerie', models.CharField(max_length=100)),
                ('ToolName', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('DateOfGiving', models.DateField()),
                ('Pin', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Pieces', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tools',
            name='Provider',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
