# Generated by Django 4.0.3 on 2022-04-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0016_shed_unfunctional_workfield_tools_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workfield',
            old_name='WorkFieldId',
            new_name='WorkField',
        ),
    ]
