# Generated by Django 4.0.3 on 2022-04-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0018_rename_toolid_unfunctional_unfunctionalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workfield',
            old_name='WorkField',
            new_name='WorkFieldId',
        ),
    ]
