# Generated by Django 4.0.3 on 2022-04-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0019_rename_workfield_workfield_workfieldid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='BillNumber',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='MaterialPrice',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='MaterialSerie',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='Pin',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='Service',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='Status',
        ),
        migrations.AddField(
            model_name='shed',
            name='Components',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shed',
            name='Detail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shed',
            name='Provider',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unfunctional',
            name='Components',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='unfunctional',
            name='Provider',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workfield',
            name='Components',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workfield',
            name='Detail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workfield',
            name='Provider',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
