# Generated by Django 4.0.3 on 2022-05-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0020_remove_materials_billnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumables',
            name='MaterialAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='histories',
            name='Pieces',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materials',
            name='OneUnity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='Quantity',
            field=models.FloatField(),
        ),
    ]
