# Generated by Django 4.0.6 on 2022-08-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0021_alter_consumables_materialamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofrajMetalics',
            fields=[
                ('CofrajMetalicId', models.AutoField(primary_key=True, serialize=False)),
                ('CofrajMetalicName', models.CharField(max_length=100)),
                ('CofrajMetalicCantitate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CofrajtTipDokas',
            fields=[
                ('CofrajtTipDokaId', models.AutoField(primary_key=True, serialize=False)),
                ('CofrajtTipDokaName', models.CharField(max_length=100)),
                ('CofrajtTipDokaCantitate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Combustibils',
            fields=[
                ('CombustibilId', models.AutoField(primary_key=True, serialize=False)),
                ('CombustibilName', models.CharField(max_length=100)),
                ('CombustibilCantitate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistorieScheles',
            fields=[
                ('HistoriesScheleId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100)),
                ('CombustibilCantitate', models.CharField(max_length=100)),
                ('DateSchela', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Popis',
            fields=[
                ('PopiDokaId', models.AutoField(primary_key=True, serialize=False)),
                ('PopiName', models.CharField(max_length=100)),
                ('PopiCantitate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchelaFatadaModularas',
            fields=[
                ('SchelaFatadaModularaId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaFatadaModularaName', models.CharField(max_length=100)),
                ('SchelaFatadaModularaCantitate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchelaFatadas',
            fields=[
                ('SchelaFatadaId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaFatadaName', models.CharField(max_length=100)),
                ('SchelaFatadaCantitate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchelaUsoaras',
            fields=[
                ('SchelaUsoaraId', models.AutoField(primary_key=True, serialize=False)),
                ('SchelaUsoaraName', models.CharField(max_length=100)),
                ('SchelaUsoaraCantitate', models.CharField(max_length=100)),
            ],
        ),
    ]
