# Generated by Django 4.0.6 on 2022-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0023_cofrajmetalics_location_cofrajttipdokas_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiescheles',
            name='Directie',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
