# Generated by Django 4.1.5 on 2025-10-08 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0025_mijloacefixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histories',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='histories',
            name='direction',
            field=models.CharField(choices=[('OUT', 'Predare (ieșire)'), ('IN', 'Returnare (intrare)'), ('ADJ', 'Ajustare')], default='OUT', max_length=8),
        ),
        migrations.AddField(
            model_name='histories',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_tool_movements', to='ToolApp.users'),
        ),
        migrations.AddField(
            model_name='histories',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='histories',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='histories',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='histories',
            name='tool_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='ToolApp.tools'),
        ),
        migrations.AddField(
            model_name='histories',
            name='user_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_movements', to='ToolApp.users'),
        ),
        migrations.AddField(
            model_name='tools',
            name='RfidTag',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='histories',
            name='DateOfGiving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histories',
            name='GiveRecive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='histories',
            name='Pieces',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histories',
            name='Tool',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='histories',
            name='ToolSerie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='histories',
            name='User',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='DateOfGiving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='Detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='MainLocation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='Pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='Provider',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='ToolSerie',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='User',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='NameAndSerie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserSerie',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='histories',
            index=models.Index(fields=['timestamp'], name='ToolApp_his_timesta_4545cd_idx'),
        ),
    ]
