# Generated by Django 4.1.5 on 2025-10-08 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0026_alter_histories_options_histories_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(choices=[('ENTER', 'Intrare'), ('EXIT', 'Ieșire')], max_length=8)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_events', to='ToolApp.users')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
