# Generated by Django 5.1.7 on 2025-10-17 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0027_presenceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('in_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('out_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('source', models.CharField(default='nfc', max_length=32)),
            ],
            options={
                'ordering': ['-in_time'],
            },
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['UserPin'], name='ToolApp_use_UserPin_a959d1_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['UserSerie'], name='ToolApp_use_UserSer_e5f6be_idx'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='ToolApp.users'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['work_date', 'user_fk'], name='ToolApp_att_work_da_4ecb81_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['user_fk', 'out_time'], name='ToolApp_att_user_fk_136353_idx'),
        ),
    ]
