# Generated by Django 4.1.5 on 2025-10-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0028_attendancesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='worksite',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presenceevent',
            name='worksite',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['worksite', 'work_date'], name='ToolApp_att_worksit_8e3467_idx'),
        ),
    ]
