# Generated by Django 4.1.5 on 2025-10-28 13:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0029_attendancesession_worksite_presenceevent_worksite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='DailyPay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('total_seconds', models.IntegerField(default=0)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('day_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_pays', to='ToolApp.users')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailypay',
            index=models.Index(fields=['user_fk', 'work_date'], name='ToolApp_dai_user_fk_da4db0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypay',
            unique_together={('user_fk', 'work_date')},
        ),
    ]
