# Generated by Django 4.1.5 on 2025-11-11 14:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0030_users_hourly_rate_dailypay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DayLeave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('CO', 'Concediu odihnă'), ('CM', 'Concediu medical'), ('ALT', 'Alt motiv')], db_index=True, default='CO', max_length=8)),
                ('hours_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pay_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_leaves', to='ToolApp.users')),
            ],
        ),
        migrations.AddIndex(
            model_name='dayleave',
            index=models.Index(fields=['user_fk', 'work_date'], name='ToolApp_day_user_fk_d60a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='dayleave',
            index=models.Index(fields=['reason'], name='ToolApp_day_reason_d1fa42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dayleave',
            unique_together={('user_fk', 'work_date')},
        ),
    ]
