# Generated by Django 4.1.5 on 2025-11-11 14:14

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0031_users_company_dayleave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('CO', 'Concediu odihnă'), ('CM', 'Concediu medical'), ('ALT', 'Alt motiv')], max_length=8)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pay_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaves', to='ToolApp.users')),
            ],
        ),
        migrations.DeleteModel(
            name='DayLeave',
        ),
        migrations.AddIndex(
            model_name='leaveday',
            index=models.Index(fields=['user_fk', 'work_date'], name='ToolApp_lea_user_fk_6ec965_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaveday',
            unique_together={('user_fk', 'work_date')},
        ),
    ]
