# Generated by Django 5.2.12 on 2026-04-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0034_attendancesession_gps_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='equipment_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='received_equipment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='trade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
