# Generated by Django 5.2.12 on 2026-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0035_users_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
