# Generated by Django 5.2.12 on 2026-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0038_users_pin_lookup'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['pin_lookup'], name='ToolApp_use_pin_loo_3f6843_idx'),
        ),
    ]
