# Generated by Django 5.2.12 on 2026-06-16 11:06

import ToolApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0041_tools_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='BatchId',
            field=models.CharField(blank=True, db_index=True, default=ToolApp.models.generate_tool_batch_id, max_length=64),
        ),
    ]
