# Generated by Django 5.2.12 on 2026-07-27 11:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0045_appuser_login_redirect_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='leaveday',
            name='reason',
            field=models.CharField(choices=[('CO', 'Concediu odihnă'), ('CM', 'Concediu medical'), ('UNPAID', 'Concediu fără plată'), ('UNEXCUSED', 'Absență nemotivată'), ('ALT', 'Alt motiv')], max_length=16),
        ),
        migrations.CreateModel(
            name='EmployeeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_employee_teams', to='ToolApp.users')),
                ('worksite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_teams', to='ToolApp.worksite')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayrollCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('required_work_days', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('-year', '-month', 'company'),
                'constraints': [models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_company_payroll_month'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='valid_payroll_month'), models.CheckConstraint(condition=models.Q(('required_work_days__gte', 1)), name='positive_required_work_days')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('housing_location', models.CharField(blank=True, default='', max_length=255)),
                ('net_salary_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_salary_ron', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('salary_advance_ron', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('salary_remainder_ron', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('food_money_enabled', models.BooleanField(default=False)),
                ('food_money_ron', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profile', to='ToolApp.users')),
                ('worksite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_profiles', to='ToolApp.worksite')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('allocated_days', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_leave_balances', to='ToolApp.users')),
            ],
            options={
                'ordering': ('-year', 'employee__UserName'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'year'), name='unique_employee_leave_balance_year')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='ToolApp.users')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ToolApp.employeeteam')),
            ],
            options={
                'ordering': ('employee__UserName',),
                'constraints': [models.UniqueConstraint(fields=('team', 'employee'), name='unique_employee_team_member')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('paid_leave', 'Concediu de odihnă'), ('unpaid_leave', 'Concediu fără plată'), ('medical_leave', 'Concediu medical'), ('other', 'Alt motiv')], max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calendar_days', models.PositiveSmallIntegerField(editable=False)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins'), ('cancelled', 'Anulat')], db_index=True, default='pending', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employee_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='ToolApp.users')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='ToolApp_lea_employe_7f1452_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_year', models.PositiveSmallIntegerField()),
                ('salary_month', models.PositiveSmallIntegerField()),
                ('payment_type', models.CharField(choices=[('salary_advance', 'Avans salariu'), ('salary_remainder', 'Rest salariu'), ('food_money', 'Bani de mâncare')], max_length=32)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payment_records', to='ToolApp.users')),
            ],
            options={
                'ordering': ('-payment_date', 'payment_type'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'salary_year', 'salary_month', 'payment_type'), name='unique_employee_salary_payment'), models.CheckConstraint(condition=models.Q(('salary_month__gte', 1), ('salary_month__lte', 12)), name='valid_salary_payment_month')],
            },
        ),
    ]
