# Generated by Django 5.2.12 on 2026-07-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0046_worksite_alter_leaveday_reason_employeeteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveday',
            name='source_leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_leave_days', to='ToolApp.leaverequest'),
        ),
    ]
