# Generated by Django 5.2.12 on 2026-07-28 08:08

from django.db import migrations, models


def move_employee_general_data(apps, schema_editor):
    Users = apps.get_model("ToolApp", "Users")
    EmployeeSalaryProfile = apps.get_model("ToolApp", "EmployeeSalaryProfile")
    for profile in EmployeeSalaryProfile.objects.all().iterator():
        Users.objects.filter(pk=profile.employee_id).update(
            hire_date=profile.hire_date,
            housing_location=profile.housing_location or "",
        )


def restore_employee_general_data(apps, schema_editor):
    Users = apps.get_model("ToolApp", "Users")
    EmployeeSalaryProfile = apps.get_model("ToolApp", "EmployeeSalaryProfile")
    for user in Users.objects.all().iterator():
        EmployeeSalaryProfile.objects.filter(employee_id=user.pk).update(
            hire_date=user.hire_date,
            housing_location=user.housing_location or "",
        )


def normalize_simplified_mobile_data(apps, schema_editor):
    LeaveRequest = apps.get_model("ToolApp", "LeaveRequest")
    EmployeeTeamMember = apps.get_model("ToolApp", "EmployeeTeamMember")

    LeaveRequest.objects.filter(leave_type__in=("medical_leave", "other")).update(
        leave_type="unpaid_leave"
    )

    seen_employee_ids = set()
    for membership in EmployeeTeamMember.objects.filter(active=True).order_by("employee_id", "pk"):
        if membership.employee_id in seen_employee_ids:
            EmployeeTeamMember.objects.filter(pk=membership.pk).update(active=False)
        else:
            seen_employee_ids.add(membership.employee_id)


class Migration(migrations.Migration):

    dependencies = [
        ("ToolApp", "0047_leaveday_source_leave_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="housing_location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(move_employee_general_data, restore_employee_general_data),
        migrations.RunPython(normalize_simplified_mobile_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="MonthlyPayrollCalendar",
        ),
        migrations.RemoveField(
            model_name="employeesalaryprofile",
            name="worksite",
        ),
        migrations.RemoveField(
            model_name="employeeteam",
            name="worksite",
        ),
        migrations.RemoveField(
            model_name="employeesalaryprofile",
            name="hire_date",
        ),
        migrations.RemoveField(
            model_name="employeesalaryprofile",
            name="housing_location",
        ),
        migrations.RemoveField(
            model_name="employeesalaryprofile",
            name="salary_remainder_ron",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="calendar_days",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="rejection_reason",
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("paid_leave", "Concediu de odihnă"),
                    ("unpaid_leave", "Concediu fără plată"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeteammember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("employee",),
                name="unique_active_employee_team_membership",
            ),
        ),
        migrations.DeleteModel(
            name="AnnualLeaveBalance",
        ),
        migrations.DeleteModel(
            name="SalaryPaymentRecord",
        ),
        migrations.DeleteModel(
            name="Worksite",
        ),
    ]
