# Generated by Django 5.2.12 on 2026-08-10 11:21

import django.db.models.deletion
from django.db import migrations, models


def normalize_active_teams(apps, schema_editor):
    EmployeeTeam = apps.get_model('ToolApp', 'EmployeeTeam')
    EmployeeTeamMember = apps.get_model('ToolApp', 'EmployeeTeamMember')
    seen_leaders = set()
    for team in EmployeeTeam.objects.filter(active=True).order_by('leader_id', 'pk'):
        if team.leader_id in seen_leaders:
            EmployeeTeam.objects.filter(pk=team.pk).update(active=False)
            EmployeeTeamMember.objects.filter(team_id=team.pk).update(active=False)
        else:
            seen_leaders.add(team.leader_id)
    EmployeeTeamMember.objects.filter(team__active=False, active=True).update(active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0048_remove_annualleavebalance_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryWorkerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Respinsă'), ('cancelled', 'Anulată'), ('expired', 'Expirată')], db_index=True, default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='employeeteam',
            name='default_worksite',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='users',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(normalize_active_teams, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='employeeteam',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('leader',), name='unique_active_employee_team_leader'),
        ),
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_team_requests', to='ToolApp.users'),
        ),
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_worker_requests_created', to='ToolApp.appuser'),
        ),
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='requester_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_requests_sent', to='ToolApp.employeeteam'),
        ),
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_worker_requests_resolved', to='ToolApp.appuser'),
        ),
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='source_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_requests_received', to='ToolApp.employeeteam'),
        ),
        migrations.AddIndex(
            model_name='temporaryworkerrequest',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='team_tmp_emp_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryworkerrequest',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='team_tmp_status_dates_idx'),
        ),
    ]
