# Generated by Django 5.2.12 on 2026-08-10 12:19

import django.db.models.deletion
from django.db import migrations, models


MODULE_MAIN_ROUTES = {
    'attendance': '/pontaj',
    'teams_schedule': '/pontaj/echipe',
    'warehouse': '/magazie',
    'human_resources': '/hr/documente',
    'tools': '/unelte',
}


def preserve_existing_access(apps, schema_editor):
    AppUser = apps.get_model('ToolApp', 'AppUser')
    AppPagePermission = apps.get_model('ToolApp', 'AppPagePermission')
    AppModuleAccess = apps.get_model('ToolApp', 'AppModuleAccess')
    EmployeeTeam = apps.get_model('ToolApp', 'EmployeeTeam')

    leaders = set(EmployeeTeam.objects.filter(active=True).values_list('leader_id', flat=True))
    for app_user in AppUser.objects.all():
        routes = set(AppPagePermission.objects.filter(
            app_user_id=app_user.pk,
            can_access=True,
        ).values_list('route', flat=True))
        modules = set()
        if routes.intersection({'/pontaj', '/pontaj/rapoarte', '/pontaj/fisa-angajat', '/dashboard', '/users/new', '/user/:id'}):
            modules.add('attendance')
        if any(route.startswith('/pontaj/echipe') or route == '/pontaj/personal-disponibil' for route in routes) or app_user.employee_id in leaders:
            modules.add('teams_schedule')
        if routes.intersection({'/magazie', '/angajati', '/materiale', '/schela', '/history', '/rafturi'}):
            modules.add('warehouse')
        if routes.intersection({'/pontaj/fisa-angajat', '/hr/documente'}):
            modules.add('human_resources')
        if routes.intersection({'/unelte', '/unelte/adauga-unealta', '/predare-unealta'}):
            modules.add('tools')

        for module_code in modules:
            AppModuleAccess.objects.update_or_create(
                app_user_id=app_user.pk,
                module_code=module_code,
                defaults={'can_access': True},
            )
            AppPagePermission.objects.update_or_create(
                app_user_id=app_user.pk,
                route=MODULE_MAIN_ROUTES[module_code],
                defaults={'can_access': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0049_team_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModuleAccess',
            fields=[
                ('AccessId', models.AutoField(primary_key=True, serialize=False)),
                ('module_code', models.CharField(choices=[('attendance', 'Pontaj'), ('teams_schedule', 'Echipe și program'), ('warehouse', 'Magazie'), ('human_resources', 'Resurse umane'), ('tools', 'Unelte')], db_index=True, max_length=32)),
                ('can_access', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to='ToolApp.appuser')),
            ],
            options={
                'indexes': [models.Index(fields=['module_code', 'can_access'], name='app_module_access_idx')],
                'unique_together': {('app_user', 'module_code')},
            },
        ),
        migrations.RunPython(preserve_existing_access, migrations.RunPython.noop),
    ]
