# Generated by Django 5.2.12 on 2026-08-11 08:24

import django.db.models.deletion
from django.db import migrations, models


def migrate_housing_locations(apps, schema_editor):
    Accommodation = apps.get_model('ToolApp', 'Accommodation')
    Users = apps.get_model('ToolApp', 'Users')
    for user in Users.objects.exclude(housing_location='').iterator():
        name = str(user.housing_location or '').strip()[:160]
        if not name:
            continue
        accommodation = Accommodation.objects.filter(name__iexact=name).first()
        if accommodation is None:
            accommodation = Accommodation.objects.create(name=name)
        user.accommodation_id = accommodation.pk
        user.save(update_fields=['accommodation'])


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0051_decouple_module_page_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='users',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='ToolApp.accommodation'),
        ),
        migrations.RunPython(migrate_housing_locations, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EmployeeDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('personal', 'Documente personale'), ('employment', 'Documente de angajare')], db_index=True, max_length=16)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='unique_employee_document_type')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('original_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('has_expiry', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ToolApp.users')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='ToolApp.employeedocumenttype')),
            ],
            options={
                'ordering': ('document_type__category', 'document_type__name', '-uploaded_at'),
            },
        ),
    ]
