# Generated by Django 5.2.12 on 2026-08-11 11:42

from django.db import migrations, models


def standardize_tool_statuses(apps, schema_editor):
    Tools = apps.get_model('ToolApp', 'Tools')
    Tools.objects.filter(Status='magazie').update(Status='functionala')
    Tools.objects.filter(Status='stricata').update(Status='nefunctionala')

    allowed = {'functionala', 'nefunctionala', 'in_lucru'}
    for tool in Tools.objects.exclude(Status__in=allowed).only('ToolId', 'AssignedTo_id'):
        tool.Status = 'in_lucru' if tool.AssignedTo_id else 'functionala'
        tool.save(update_fields=['Status'])


def restore_legacy_tool_statuses(apps, schema_editor):
    Tools = apps.get_model('ToolApp', 'Tools')
    Tools.objects.filter(Status='functionala').update(Status='magazie')
    Tools.objects.filter(Status='nefunctionala').update(Status='stricata')


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0052_accommodation_users_accommodation_and_more'),
    ]

    operations = [
        migrations.RunPython(standardize_tool_statuses, restore_legacy_tool_statuses),
        migrations.AlterField(
            model_name='tools',
            name='Status',
            field=models.CharField(choices=[('functionala', 'Funcțional'), ('nefunctionala', 'Nefuncțional'), ('in_lucru', 'În lucru')], db_index=True, default='functionala', max_length=32),
        ),
    ]
