# Generated by Django 5.2.12 on 2026-08-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0053_alter_tools_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='ExpiryDate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
