# Generated by Django 5.2.12 on 2026-08-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0055_leave_request_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='request_type',
            field=models.CharField(choices=[('temporary', 'Temporară'), ('permanent', 'Permanentă')], db_index=True, default='temporary', max_length=16),
        ),
        migrations.AddField(
            model_name='temporaryworkerrequest',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
