# Generated by Django 4.2 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0056_team_notifications_and_permanent_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='checkin_photo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='data_processing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='data_processing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
