# Generated by Django 4.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0057_attendancesession_checkin_photo_and_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='checkout_photo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
