# Generated by Django 4.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0058_attendancesession_checkout_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='expiry_notification_sent_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
