# Generated by Django 5.2.12 on 2026-08-31 07:25

import django.db.models.deletion
import datetime
from django.db import migrations, models


def seed_escalation_configs(apps, schema_editor):
    Config = apps.get_model('ToolApp', 'AttendanceAlertEscalationConfig')
    Config.objects.get_or_create(level=1, defaults={
        'role_name': 'Nivel 1', 'alert_time': datetime.time(7, 55), 'active': True,
    })
    Config.objects.get_or_create(level=2, defaults={
        'role_name': 'Nivel 2', 'alert_time': datetime.time(8, 10), 'active': True,
    })


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0073_team_dashboard_and_absence_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAlertEscalationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2')], unique=True)),
                ('role_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('alert_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_escalation_configs', to='ToolApp.appuser')),
            ],
            options={
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlertRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Alertă inițială'), (1, 'Nivel 1'), (2, 'Nivel 2')])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='started', max_length=32)),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('emails_sent', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['work_date', 'level'], name='attendance_run_level_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlertCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Alertă inițială'), (1, 'Nivel 1'), (2, 'Nivel 2')])),
                ('worksite', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_method', models.CharField(blank=True, choices=[('check_in', 'Check-in'), ('marked_absent', 'Marcat absent'), ('leave', 'Concediu / absență'), ('not_required', 'Nu se pontează'), ('inactive', 'Angajat inactiv'), ('no_longer_eligible', 'Nu mai este eligibil')], default='', max_length=32)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_alert_cases', to='ToolApp.users')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_attendance_alert_cases', to='ToolApp.appuser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_alert_cases', to='ToolApp.employeeteam')),
            ],
            options={
                'ordering': ('-work_date', 'level', 'team__name', 'employee__UserName'),
                'indexes': [models.Index(fields=['work_date', 'level', 'resolved_at'], name='attendance_case_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date', 'level'), name='unique_attendance_alert_case_level_day')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlertDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Alertă inițială'), (1, 'Nivel 1'), (2, 'Nivel 2')])),
                ('role_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToolApp.appuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work_date', 'level'), name='unique_attendance_dispatch_level_day')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlertEscalationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Alertă inițială'), (1, 'Nivel 1'), (2, 'Nivel 2')])),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_escalation_notifications', to='ToolApp.appuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'work_date', 'level'), name='unique_attendance_escalation_notification')],
            },
        ),
        migrations.RunPython(seed_escalation_configs, migrations.RunPython.noop),
    ]
