# Generated by Django 5.2.12 on 2026-08-31 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0074_attendancealertescalationconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceabsencemark',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='attendanceabsencemark',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceabsencemark',
            name='source',
            field=models.CharField(choices=[('team_leader', 'Șef de echipă'), ('level_1', 'Nivel 1'), ('automatic_level_2', 'Automat la Nivel 2')], default='team_leader', max_length=32),
        ),
        migrations.AddField(
            model_name='attendancealertcase',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancealertcase',
            name='escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_attendance_alert_cases', to='ToolApp.appuser'),
        ),
        migrations.AddField(
            model_name='attendancealertcase',
            name='escalation_source',
            field=models.CharField(blank=True, choices=[('scheduled_0810', 'Nepontat până la 08:10'), ('marked_by_level_1', 'Marcat lipsă de Nivel 1'), ('marked_by_team_leader', 'Marcat lipsă de Șef echipă')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='attendancealertcase',
            name='marked_absent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceabsencemark',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_absences_marked', to='ToolApp.appuser'),
        ),
        migrations.CreateModel(
            name='AttendanceLateCheckinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToolApp.appuser')),
            ],
        ),
    ]
