# Generated by Django 5.2.12 on 2026-08-31 14:01

import django.db.models.deletion
import re
import unicodedata
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def _username_part(value):
    text = unicodedata.normalize('NFD', str(value or ''))
    text = ''.join(character for character in text if unicodedata.category(character) != 'Mn')
    return re.sub(r'[^a-zA-Z0-9]+', '.', text).strip('.').lower() or 'angajat'


def sync_existing_employee_accounts(apps, schema_editor):
    Users = apps.get_model('ToolApp', 'Users')
    AppUser = apps.get_model('ToolApp', 'AppUser')
    for employee in Users.objects.all().iterator():
        active = (
            employee.person_type == 'employee'
            and employee.active
            and employee.employment_status == 'active'
        )
        account = AppUser.objects.filter(employee_id=employee.pk).first()
        if not active:
            if account and account.is_active:
                account.is_active = False
                account.save(update_fields=('is_active', 'updated_at'))
            continue
        if account:
            account.is_active = True
            account.login_redirect_path = '/team-dashboard'
            # Copiem hashul Django deja calculat pentru angajat. Nu refacem
            # PBKDF2 pentru fiecare persoană în timpul migrării; pe serverele
            # mici această buclă putea dura minute întregi.
            if str(getattr(employee, 'pin_hash', '') or '').strip():
                account.pin_hash = employee.pin_hash
            account.save(update_fields=('is_active', 'login_redirect_path', 'pin_hash', 'updated_at'))
            continue
        parts = [_username_part(part) for part in str(employee.UserName or '').split() if part.strip()]
        base = '.'.join(parts[:2]) or f'angajat.{employee.pk}'
        username = base
        suffix = 2
        while AppUser.objects.filter(username__iexact=username).exists():
            username = f'{base}.{suffix}'
            suffix += 1
        AppUser.objects.create(
            employee_id=employee.pk,
            username=username,
            # PIN-urile legacy rămase în UserPin sunt validate și hash-uite
            # lazy la prima autentificare.
            pin_hash=(str(getattr(employee, 'pin_hash', '') or '').strip() or make_password(None)),
            is_active=True,
            login_redirect_path='/team-dashboard',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0075_attendanceabsencemark_escalation_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='employee_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PortalTeamTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_role', models.CharField(choices=[('team_leader', 'Șef de echipă'), ('supervisor', 'Supervisor')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('source_approval', models.CharField(choices=[('not_required', 'Nu este necesară'), ('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Respinsă')], default='not_required', max_length=20)),
                ('destination_approval', models.CharField(choices=[('not_required', 'Nu este necesară'), ('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Respinsă')], default='pending', max_length=20)),
                ('source_decided_at', models.DateTimeField(blank=True, null=True)),
                ('destination_decided_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Respinsă'), ('cancelled', 'Anulată')], db_index=True, default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_transfer_destination_decisions', to='ToolApp.appuser')),
                ('destination_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_transfer_requests_in', to='ToolApp.employeeteam')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_transfer_requests', to='ToolApp.users')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_transfer_requests_created', to='ToolApp.appuser')),
                ('source_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_transfer_source_decisions', to='ToolApp.appuser')),
                ('source_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_transfer_requests_out', to='ToolApp.employeeteam')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='portal_transfer_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('employee',), name='unique_pending_portal_transfer_employee')],
            },
        ),
        migrations.RunPython(sync_existing_employee_accounts, migrations.RunPython.noop),
    ]
