# Generated by Django 5.2.12 on 2026-09-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0082_import_home_ticket_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bonus_lunar_sef_echipa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='data_start_sef_echipa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='data_ultimei_plati_bonus_sef',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='suma_bonus_bilet_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
