# Generated by Django 5.2.12 on 2026-09-08 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0083_bonus_bilet_si_sef_echipa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmoduleaccess',
            name='module_code',
            field=models.CharField(choices=[('attendance', 'Pontaj'), ('construction_sites', 'Șantiere'), ('teams_schedule', 'Echipe și program'), ('team_dashboard', 'Team Dashboard'), ('warehouse', 'Magazie'), ('tools', 'Unelte')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('planned', 'Planificat'), ('active', 'Activ'), ('paused', 'Suspendat'), ('completed', 'Finalizat'), ('archived', 'Arhivat')], db_index=True, default='active', max_length=16)),
                ('client', models.CharField(blank=True, max_length=160)),
                ('manager', models.CharField(blank=True, max_length=160)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('budget__gte', 0), ('budget__isnull', True), _connector='OR'), name='site_budget_nonnegative'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date')), ('start_date__isnull', True), ('end_date__isnull', True), _connector='OR'), name='site_dates_ordered')],
            },
        ),
        migrations.CreateModel(
            name='SiteAttendancePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_points', to='ToolApp.constructionsite')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('actor', models.CharField(max_length=180)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ToolApp.constructionsite')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('materials', 'Materiale'), ('equipment', 'Utilaje și închirieri'), ('transport', 'Transport'), ('subcontractors', 'Subcontractori'), ('accommodation', 'Cazare'), ('overhead', 'Cheltuieli indirecte'), ('other', 'Alte costuri')], max_length=24)),
                ('description', models.CharField(max_length=300)),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='ToolApp.constructionsite')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['site', 'date'], name='site_expense_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='site_expense_positive')],
            },
        ),
    ]
