# Generated by Django 5.2.12 on 2026-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0084_construction_site_cost_centres'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='tesa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_tesa',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'tesa')), fields=('user_fk', 'work_date'), name='unique_tesa_confirmation_per_day'),
        ),
    ]
