# Generated by Django 5.2.12 on 2026-09-15 07:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0085_tesa_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmoduleaccess',
            name='module_code',
            field=models.CharField(choices=[('attendance', 'Pontaj'), ('construction_sites', 'Șantiere'), ('teams_schedule', 'Echipe și program'), ('team_dashboard', 'Team Dashboard'), ('warehouse', 'Magazie'), ('tools', 'Unelte'), ('flota', 'Flotă')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='TipDocumentUtilaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120, unique=True)),
                ('blocheaza_utilizarea', models.BooleanField(default=False)),
                ('zile_avertizare', models.PositiveSmallIntegerField(default=30)),
                ('activ', models.BooleanField(db_index=True, default=True)),
                ('documente_angajat_necesare', models.ManyToManyField(blank=True, related_name='tipuri_document_utilaj_autorizate', to='ToolApp.employeedocumenttype')),
            ],
            options={
                'ordering': ('nume',),
            },
        ),
        migrations.CreateModel(
            name='Utilaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_intern', models.CharField(db_index=True, max_length=40, unique=True)),
                ('denumire', models.CharField(max_length=160)),
                ('nr_inmatriculare', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('categorie', models.CharField(choices=[('autoturism', 'Autoturism'), ('autoutilitara', 'Autoutilitară'), ('excavator', 'Excavator'), ('macara', 'Macara'), ('stivuitor', 'Stivuitor'), ('generator', 'Generator'), ('altele', 'Altele')], db_index=True, default='altele', max_length=24)),
                ('tip_contor', models.CharField(choices=[('km', 'Kilometri'), ('ore', 'Ore motor'), ('fara', 'Fără contor')], default='fara', max_length=8)),
                ('contor_curent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stare', models.CharField(choices=[('disponibil', 'Disponibil'), ('in_lucru', 'În lucru'), ('defect', 'Defect'), ('service', 'Service')], db_index=True, default='disponibil', max_length=16)),
                ('token_qr', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('activ', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('santier_curent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilaje', to='ToolApp.constructionsite')),
                ('tipuri_document_necesare', models.ManyToManyField(blank=True, related_name='utilaje', to='ToolApp.tipdocumentutilaj')),
            ],
            options={
                'ordering': ('cod_intern',),
            },
        ),
        migrations.CreateModel(
            name='SesiuneUtilaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inceput', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sfarsit', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('contor_inceput', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contor_sfarsit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gps_latitudine', models.FloatField(blank=True, null=True)),
                ('gps_longitudine', models.FloatField(blank=True, null=True)),
                ('gps_precizie_m', models.FloatField(blank=True, null=True)),
                ('motiv_inchidere', models.CharField(blank=True, choices=[('predare', 'Predare de către angajat'), ('depontare', 'Închis la depontare'), ('final_zi', 'Închis automat la finalul zilei')], default='', max_length=16)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiuni_utilaj', to='ToolApp.users')),
                ('attendance_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiuni_utilaj', to='ToolApp.attendancesession')),
                ('santier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiuni_utilaj', to='ToolApp.constructionsite')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiuni', to='ToolApp.utilaj')),
            ],
            options={
                'ordering': ('-inceput',),
                'indexes': [models.Index(fields=['angajat', 'sfarsit'], name='utilaj_session_employee_idx'), models.Index(fields=['utilaj', 'sfarsit'], name='utilaj_session_machine_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sfarsit__isnull', True)), fields=('utilaj',), name='unique_open_session_per_utilaj'), models.UniqueConstraint(condition=models.Q(('sfarsit__isnull', True)), fields=('angajat',), name='unique_open_utilaj_per_employee')],
            },
        ),
        migrations.CreateModel(
            name='DocumentUtilaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_expirare', models.DateField(blank=True, db_index=True, null=True)),
                ('fisier', models.FileField(upload_to='utilaj_documents/%Y/%m/')),
                ('nume_fisier_original', models.CharField(blank=True, default='', max_length=255)),
                ('expiry_notification_sent_for', models.DateField(blank=True, null=True)),
                ('expiry_notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documente', to='ToolApp.tipdocumentutilaj')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documente', to='ToolApp.utilaj')),
            ],
            options={
                'ordering': ('tip__nume', '-updated_at'),
                'constraints': [models.UniqueConstraint(fields=('utilaj', 'tip'), name='unique_document_type_per_utilaj')],
            },
        ),
    ]
