# Generated by Django 5.2.12 on 2026-09-15 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0086_alter_appmoduleaccess_module_code_tipdocumentutilaj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilaj',
            name='an_fabricatie',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilaj',
            name='proprietar',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='utilaj',
            name='serie_sasiu',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='utilaj',
            name='tarif_intern',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='utilaj',
            name='tip_proprietate',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='AlimentareUtilaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('litri', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('angajat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alimentari_utilaj', to='ToolApp.users')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alimentari', to='ToolApp.utilaj')),
            ],
            options={
                'ordering': ('-data', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FleetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiune', models.CharField(db_index=True, max_length=64)),
                ('actor', models.CharField(max_length=180)),
                ('detalii', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilaj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ToolApp.utilaj')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncercareUtilajBlocata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(db_index=True, max_length=64)),
                ('motiv', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('angajat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incercari_utilaj_blocate', to='ToolApp.users')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incercari_blocate', to='ToolApp.utilaj')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SesizareDefectUtilaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriere', models.TextField()),
                ('fotografie', models.FileField(blank=True, null=True, upload_to='utilaj_defects/%Y/%m/')),
                ('gravitate', models.CharField(choices=[('mica', 'Mică'), ('medie', 'Medie'), ('grava', 'Gravă')], db_index=True, default='medie', max_length=12)),
                ('status', models.CharField(choices=[('nou', 'Nou'), ('in_lucru', 'În lucru'), ('rezolvat', 'Rezolvat')], db_index=True, default='nou', max_length=16)),
                ('responsabil', models.CharField(blank=True, default='', max_length=160)),
                ('cost_reparatie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observatii_rezolvare', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raportat_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defecte_utilaj_raportate', to='ToolApp.users')),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defecte', to='ToolApp.utilaj')),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
    ]
