# Generated by Django 5.2.12 on 2026-09-15 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0087_utilaj_an_fabricatie_utilaj_proprietar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUtilajVersiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_expirare', models.DateField(blank=True, db_index=True, null=True)),
                ('fisier', models.FileField(blank=True, upload_to='utilaj_document_history/%Y/%m/')),
                ('nume_fisier_original', models.CharField(blank=True, default='', max_length=255)),
                ('incarcat_de', models.CharField(blank=True, default='', max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiuni', to='ToolApp.documentutilaj')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RevizieUtilaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=180)),
                ('data_scadenta', models.DateField(blank=True, db_index=True, null=True)),
                ('contor_scadenta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('planificata', 'Planificată'), ('finalizata', 'Finalizată'), ('anulata', 'Anulată')], db_index=True, default='planificata', max_length=16)),
                ('observatii', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finalizata_la', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilaj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revizii', to='ToolApp.utilaj')),
            ],
            options={
                'ordering': ('status', 'data_scadenta', 'contor_scadenta', 'id'),
            },
        ),
    ]
