# Generated by Django 5.2.12 on 2026-09-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolApp', '0089_users_is_driver'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='unique_tesa_confirmation_per_day',
        ),
    ]
